# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    - uses: actions/checkout@v2

    
    
    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
        
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
    
    - name: test
      run: |
        user='${{ secrets.USER }}'
        pwd='${{ secrets.PWD }}'

        
        python3 hello.py
       
